# Generated by Django 3.2.7 on 2021-10-03 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('provider', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_supplies_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_request.supplies_request')),
            ],
        ),
    ]
