# Generated by Django 3.2.7 on 2021-10-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuppliesRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('provider', models.CharField(max_length=200, verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='RequestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('cost_d', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coste en Dolares')),
                ('cost_b', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Coste en Bolívares')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Producto')),
                ('id_supplies_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_request.suppliesrequest', verbose_name='Pedido')),
            ],
        ),
    ]
