# Generated by Django 3.2.7 on 2021-10-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliesrequest',
            name='provider',
            field=models.CharField(max_length=255, verbose_name='Proveedor'),
        ),
    ]
