# Generated by Django 3.2.7 on 2021-10-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('supplies_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_content',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
