# Generated by Django 3.2.7 on 2021-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211003_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, db_column='descripcion', max_length=500, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
    ]
